version: "3.9"
services:
  trainer:
    image: "zauberzeug/yolor_trainer_node:${TAG-latest}"
    ipc: host
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - SERVER_BASE_URL=https://learning-loop.ai
      - WEBSOCKET_BASE_URL=wss://learning-loop.ai
    volumes:
      - ./trainer:/app
      - ./data:/data
    build:
      context: .
      args:
        IMAGE: nvcr.io/nvidia/pytorch:20.11-py3
    command: /app/start.sh debug

  detector:
    image: "zauberzeug/yolor_detector_node:${TAG-latest}"
    ipc: host
    volumes:
      - ./detector:/app
      - ./data:/data
    build:
      context: .
      args:
        IMAGE: nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3
    command: /app/start.sh debug
