version: "3.9"
services:
  trainer:
    image: "zauberzeug/yolor_trainer_node:${TAG-latest}"
    ipc: host
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./trainer:/app
    build: .
    command: /app/start.sh debug
