version: "3.9"
services:
  trainer:
    image: "zauberzeug/yolor_trainer_node:${TAG-latest}"
    ipc: host
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - SERVER_BASE_URL=https://learning-loop.ai
      - WEBSOCKET_BASE_URL=wss://learning-loop.ai
    volumes:
      - ./trainer:/app
      - ./data:/data
    build: .
    command: /app/start.sh debug
