name: Run Tests

on: [push]

jobs:
  pytest:
    runs-on: [self-hosted, gpu]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          cd trainer
          ./docker.sh b
          pwd
          docker run -d -it --rm -v /home/zauberzeug/data:/data -e HOST= -h n6 -e USERNAME= -e PASSWORD= --name yolov5_trainer_node --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all --gpus all --ipc host zauberzeug/yolov5-trainer:latest-dev
          docker ps
          docker exec -T yolov5-trainer pytest -v'
          nvidia-smi
