name: Run Tests

on: [push]

jobs:
  pytest:
    runs-on: [self-hosted, gpu]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker stop yolov5_trainer_node_github_action | echo "Nothing to do. No container running."

          cd trainer
          ./docker.sh b

          docker run -d -it --rm -v /home/zauberzeug/data:/data -h n6 -e LOOP_HOST=$LOOP_HOST  -e LOOP_USERNAME=$LOOP_USERNAME -e PASSWORD=$LOOP_PASSWORD --name yolov5_trainer_node_github_action --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all --gpus all --ipc host zauberzeug/yolov5-trainer:latest-dev

          docker exec yolov5_trainer_node_github_action pytest -v
          nvidia-smi
