name: Run Tests

on: [push]

jobs:
  pytest:
    runs-on: [self-hosted, gpu]
    steps:
      - uses: actions/checkout@v2
      - name: cml_ruh
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nvidia-smi
