name: Run Tests

on: [push]

jobs:
  pytest:
    runs-on: [self-hosted, gpu]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          cd trainer
          ./docker.sh b
          docker-compose -p loop exec -T mock_detector pytest -v'
          nvidia-smi
