name: Run Tests

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: test
        run: |
          cd trainer
          docker.sh b
          docker.sh run
          docker exec yolov5_trainer_node pytest -v
        env:
          LOOP_HOST: preview.learning-loop.ai
          LOOP_USERNAME: admin
          LOOP_PASSWORD: ${{ secrets.LEARNING_LOOP_ADMIN_PASSWORD }}
  slack:
    needs:
      - pytest
    if: always() # also execute when pytest fails
    runs-on: ubuntu-latest
    steps:
      - name: Determine if we need to notify
        uses: Jimdo/should-i-notify-action@main
        id: should_notify
        with:
          needs_context: ${{ toJson(needs) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack workflow notification
        if: steps.should_notify.outputs.should_send_message == 'yes'
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GIT_HUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_DEEPLEARNING_CI_WEBHOOK }}
          channel: "deeplearning-ci"
          name: "yolov5 Trainer"
