name: Run Tests

on: [push]

jobs:
  pytest:
    runs-on: [self-hosted, gpu]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          cd trainer
          ./docker.sh b
          pwd
          ./docker.sh run
          docker ps
          docker exec -T yolov5-trainer pytest -v'
          nvidia-smi
